### PR TITLE
Updates on EPIP XSD and example

### PR DESCRIPTION
**Pull request by anasfouITxPT**
I have added the updated files. Need to delete the zip files...

### CODE REVIEW

**Review by skinkie — CHANGES_REQUESTED** [review]
The files should not have an _updated suffix. But should replace the original files.

**Comment by skinkie** [comment]
The zip file must be deleted.

**Comment by anasfouITxPT** [comment]
> The files should not have an _updated suffix. But should replace the original files.
How can I replace and delete? I only found "upload files", "create files". 


> The zip file must be deleted.

**Comment by skinkie** [comment]
I would say: start over.
1. Unzip the files.
2. Rename the _updated files, to the "current filename".
3. Only check in the updated files, not the zip file.

**Comment by Aurige** [comment]
> > The files should not have an _updated suffix. But should replace the original files.
> > How can I replace and delete? I only found "upload files", "create files".
> 
> > The zip file must be deleted.

Do you use Github Desktop ? ... that's probably the easiest way to go for you: so you setup everything on your computer and then just "push" everything

**Review by skinkie — COMMENTED** [review]
This is perfect!

**Comment by anasfouITxPT** [comment]
So I need to "verify" what I want to add on the request... Can you see also the description update I have on my "fork"?  Or I guess I need to added here...:/ Is the following...
_Data4PT (Programme SUpport Action for Transmodel implementation) provides an XSD that adapts to European Passenger Information profile (EPIP). This tool aims to enable datasets validation against this minimum EU profile while also to be used as a base for national profiles specification, depending on national needs.  A graphic interactive technical presentation is available here https://data4pt.org/wiki/NeTEX#NeTEx_EPIP_

I am installing now the desktop version to make it easier for the NeTEx-light updates... hopefully... :/

**Comment by skinkie** [comment]
You should still 'delete' the other files.

**Review by skinkie — APPROVED** [review]

**Comment by skinkie** [comment]
@anasfouITxPT good job!

**Comment by anasfouITxPT** [comment]
sorry I added again the example, I think I deleted it... by the way this github is not users' friendly

**Comment by anasfouITxPT** [comment]
Hi Stefan, 
I need to update this files on EPIP and NeTEx light but I tried to do a pull request but I do not remember the process :(. I tried to upload files and then make a pull request but I think I am not allowed... May you remind me the steps? :)

[XSD_reduced (1).zip](https://github.com/NeTEx-CEN/NeTEx-Profile-EPIP/files/8959641/XSD_reduced.1.zip)
[XSD_EPIP.zip](https://github.com/NeTEx-CEN/NeTEx-Profile-EPIP/files/8959642/XSD_EPIP.zip)

**Pull request merged**
